services:
- type: web
  name: movie-time
  env: python
  plan: starter
  buildCommand: ./build.sh
  startCommand: gunicorn FinalProject.wsgi:application
  autoDeploy: false
  envVars:
    - key: DATABASE_URL
        fromDatabase:
          name: movietime
          property: connectionString
    - key: WEB_CONCURRENCY
      value: 4
    - key: DJANGO_SECRET_KEY
      generateValue: true
    - key: DJANGO_ADMIN_URL
      generateValue: true
    - key: DJANGO_SETTINGS_MODULE
      value: FinalProject.settings